TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -1
  max_vel_theta: 1 #1.5
  min_vel_theta: -1.0 
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 3.2 #1.5
  acc_lim_x: 1
  acc_lim_y: 1
  holonomic_robot: false

