TrajectoryPlannerROS:
  max_vel_x: 0.38
  min_vel_x: 0.005
  max_vel_theta: 2 #1.5
  min_vel_theta: -1.5 
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 1.7 #1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.4
  holonomic_robot: false

