obstacle_range: 2.3
raytrace_range: 2.6
footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
inflation_radius: 0.22
transform_tolerance: 0.2

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /laser/scan
  marking: true
  clearing: true

map_type: costmap

