obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
inflation_radius: 0.55
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /laser/scan
  marking: true
  clearing: true

map_type: costmap


