global_costmap:
  global_frame: map
  robot_base_frame: laser  # line of error
  update_frequency: 4.0 #before: 5.0
  publish_frequency: 1.0 #before 0.5
  static_map: true
  transform_tolerance: 0.2
  cost_scaling_factor: 10.0
  inflation_radius: 0.22

