local_costmap:
  global_frame: odom
  robot_base_frame: laser # line of error
  update_frequency: 4.0 #before 5.0
  publish_frequency: 1.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2 
  height: 2
  resolution: 0.025 #increase to for higher res 0.025
  transform_tolerance: 0.2
  cost_scaling_factor: 10
  inflation_radius: 0.22

