TrajectoryPlannerROS:
  max_vel_x: 4.8
  min_vel_x: -1.2
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.0
  acc_lim_theta: 4.2
  acc_lim_x: 3.6
  acc_lim_y: 3.6
  holonomic_robot: false
  meter_scoring: true

